### ISSUE TITLE
Performance comparison with yolov5n

### ISSUE THREAD

**Issue by thuangb** [ppogg/YOLOv5-Lite#87]
Hi, I want to know more about the performance of new model form yolov5 which is yolov5n. Is it better than v5Lite-s model or worse ?

**Comment by ppogg** [comment]
The performance of the two models is similar, but the target architecture is different. v5lite is suitable for arm architecture cpu, yolov5n is more suitable for arm architecture gpu

**Comment by thuangb** [comment]
Oh, so for example if I want to run object detection on raspberry pi then v5lite-s is more suitable than yolov5n ?

**Comment by ppogg** [comment]
You can test it and tell me the result. In addition, please use C++ inference library instead of python when testing.
![image](https://user-images.githubusercontent.com/82716366/147196393-139ac56c-71fd-4e7e-a89b-b53c1e887476.png)
The first three lines are the speed of the v5lites model, and the reasoning frame is ncnn

**Comment by thuangb** [comment]
Thanks, I will try it and show some report. I close this for now
